Repository smgraywood/stacks, pull requests merged in 2023-04, with the labels that each got.

#13 Frontend - Add Styling for Landing Page
  public/css/styles.css
  public/images/logo.png
  views/landing.ejs
  views/partials/head.ejs
Labels: frontend

#18 Frontend - Add index page architecture and styling
  public/css/styles.css
  public/images/wood.jpeg
  routes/index.js
  views/index.ejs
  views/partials/footer.ejs
Labels: frontend

#20 Back & Frontend: Remove stack from bookSchema + add stacks views
  models/stack.js
  views/stacks/new.ejs
  views/stacks/show.ejs
Labels: frontend, backend

#22 Frontend - Add new views for stacks and books
  models/stack.js
  views/books/new.ejs
  views/partials/header.ejs
  views/stacks/index.ejs
  views/stacks/new.ejs
Labels: frontend

#26 Backend - Add routes for stacks/new, books/new, and index. All forms adding to …
  controllers/books.js
  controllers/stacks.js
  models/book.js
  models/stack.js
  models/user.js
  views/books/index.ejs
  views/books/new.ejs
  views/stacks/index.ejs
  views/stacks/new.ejs
Labels: backend

#28 Backend - wip: add book to stack
  controllers/books.js
  controllers/stacks.js
  routes/books.js
  views/stacks/index.ejs
  views/stacks/show.ejs
Labels: backend

#29 Backend: Complete add book to stack functionality
  controllers/books.js
  controllers/stacks.js
  models/stack.js
  routes/books.js
  routes/stacks.js
  views/stacks/show.ejs
Labels: backend

#31 Frontend - add styling to books/index page to bring it in line with design brief
  public/css/styles.css
  views/books/index.ejs
Labels: frontend

#32 Frontend - reformat architecture of form of books/new page and add styling to books/new page
  models/book.js
  public/css/styles.css
  public/images/icons8-delete-80.png
  public/images/icons8-pencil-drawing-80.png
  views/books/new.ejs
Labels: frontend

#34 Frontend - fix to links to make them display correctly, fix to large-plant image
  models/book.js
  public/css/styles.css
  views/books/index.ejs
  views/books/new.ejs
  views/landing.ejs
  views/partials/header.ejs
  views/stacks/index.ejs
  views/stacks/new.ejs
Labels: frontend

#35 Frontend - Add mobile responsiveness for landing, /index, and /new pages
  public/css/styles.css
  views/books/index.ejs
Labels: frontend

#38 Backend: Add update stack name functionality
  controllers/stacks.js
  routes/stacks.js
  views/stacks/edit.ejs
Labels: backend

#40 Backend: Add authorization
  config/ensureLoggedIn.js
  controllers/stacks.js
  routes/stacks.js
Labels: backend

#41 Front End/Back End - create book edit functionality
  controllers/books.js
  routes/books.js
  views/books/edit.ejs
Labels: frontend, backend

#42 Frontend - Change "placeholders" to "values" for books and stacks editing
  views/books/edit.ejs
  views/stacks/edit.ejs
Labels: frontend

#43 Frontend - Add browser and mobile styling to books/edit page
  public/css/styles.css
  views/books/edit.ejs
  views/books/index.ejs
  views/books/show.ejs
Labels: frontend

#44 Backend: Books connect to user & add auth for book routes
  controllers/books.js
  routes/books.js
Labels: backend

#45 Frontend - fix styling issues across pages
  public/css/styles.css
  views/books/edit.ejs
  views/books/new.ejs
  views/books/show.ejs
  views/partials/footer.ejs
  views/stacks/edit.ejs
Labels: frontend

#46 Documentation - Add readme images and edit readme file
  README.md
  public/images/README_images/figma.png
  public/images/README_images/login.png
Labels: documentation

#47 Documentation: Add comments to routes, models, controllers, & config
  config/database.js
  config/ensureLoggedIn.js
  config/passport.js
  controllers/books.js
  controllers/index.js
  controllers/landing.js
  controllers/stacks.js
  models/book.js
  models/stack.js
  models/user.js
  routes/index.js
  routes/landing.js
  routes/stacks.js
  server.js
Labels: documentation

#49 Backend: Limit number of stacks a user can create
  controllers/stacks.js
  views/addStacksError.ejs
Labels: frontend, backend

#52 Frontend: Update add-stack-table width
  public/css/styles.css
Labels: frontend

#54 Backend: Fix updateBook func so it includes favoriteQuote
  controllers/books.js
Labels: backend
